---
- hosts: localhost
  connection: local
  #Ansible1.9からはsudoではなくbecomeを使ったほうが良いらしい
  sudo: true
  vars: 
      locale: ja_JP.UTF-8
      zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo
  tasks:
    - name: update sources.list
      command: sed -i -e 's%http://.*.ubuntu.com%http://ftp.jaist.ac.jp/pub/Linux%g' /etc/apt/sources.list
    - name: update a local machine
      apt: update_cache=yes 
    - name: upgrade a local machine
      apt: upgrade=full
    - name: set locale
      command: /usr/sbin/update-locale LANGUAGE={{locale}} LC_ALL={{locale}} LANG={{locale}}
    - name: set localtime
      file: >
         src={{zoneinfo_path}}
         dest="/etc/localtime"
         state=link
         force=yes
