---
- hosts: localhost
  connection: local
  #Ansible1.9からはsudoではなくbecomeを使ったほうが良いらしい
  sudo: true
  vars: 
      locale: ja_JP.UTF-8
      zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo
      mail: "email"
      name: "name"
  tasks:
    - name: update sources.list
      command: sed -i -e 's%http://.*.ubuntu.com%http://ftp.jaist.ac.jp/pub/Linux%g' /etc/apt/sources.list
    - name: update a local machine
      apt: update_cache=yes 
    - name: install packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
          - language-pack-ja
          - software-properties-common
    - name: add apt-repo
      apt_repository: repo='ppa:ansible/ansible'
    - name: update a local machine
      apt: update_cache=yes 
    - name: upgrade a local machine
      apt: upgrade=full
    - name: set locale
      command: /usr/sbin/update-locale LANGUAGE={{locale}} LC_ALL={{locale}} LANG={{locale}}
    - name: set localtime
      file: >
         src={{zoneinfo_path}}
         dest="/etc/localtime"
         state=link
         force=yes
    - name: set git config user.email
      command: /usr/bin/git config --global user.email {{mail}}
    - name: set git config user.name
      command: /usr/bin/git config --global user.name {{name}} 
